version: '3.9'

services:
  flask-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: opinions-app
    env_file:
      - ../.env
    ports:
      - "${FLASK_PORT}:5000"
    command: "sh /app/entrypoint.sh"
    depends_on:
      - postgres
    volumes:
      - ..:/app/
